---
title: "Microbial Signatures Data Munging"
package: MungeCuratedMGS
output:
  BiocStyle::html_document:
    number_sections: yes
    toc: yes
    toc_depth: 4
abstract: |
  Just data munging.
vignette: |
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

# Installation

```{r eval=FALSE}
BiocManager::install('seandavi/MungeCuratedMGS')
```

# Data entities

```{r message=FALSE, warning=FALSE}
library(MungeCuratedMGS)
```

# Authentication

Run only once to authenticate, before running vignette (not evaluated in vignette):
```{r eval=FALSE}
library(googlesheets)
token = gs_auth()
saveRDS(token, file = "/tmp/googlesheets_token.rds")
```

Then run with the vignette, each time:
```{r eval=FALSE}
library(googlesheets)
suppressMessages(gs_auth(token = "/tmp/googlesheets_token.rds", verbose = FALSE))
```


## Ontologies

### EFO

```{r efo, cache=TRUE}
efo = get_efo()
head(efo)
```

### UBERON

```{r uberon, cache=TRUE}
uberon = get_uberon()
head(uberon)
```

Ontologies can be combined like so:

```{r}
library(dplyr)
full_ontologies = dplyr::bind_rows(uberon, efo)
```

## NCBI Taxonomy

### Names and Taxon IDs

```{r taxon_names, cache=TRUE}
taxon_dir = get_taxon_dump_files()
taxon_id_names = get_taxon_names(taxon_dir)
head(taxon_id_names, 10)
```

## Write all curation tables as csv files

```{r}
study <- create_study_table()
signature <- create_signature_table()
signature[["Study"]] <- create_keys("Study ", study)
signature[["Page Name"]] <- create_keys("Signature ", signature)
signature <- unique(signature)
study[["Page Name"]] <- create_keys("Study ", study)
study <- unique(study)
write.csv(study, file="studies.csv", row.names = FALSE)
write.csv(signature, file="signatures.csv", row.names = FALSE)
```

